### ISSUE TITLE
pod install step failing

### ISSUE THREAD

**Issue by rajohns08** [CCExtractor/rutorrent-flutter#57]
I'm currently updating Xcode to see if that could be the issue. I was on 11.3, and I'm about to try 12.4. I just wanted to file this in case someone else in the future comes across this.

```
% pod install
Traceback (most recent call last):
	20: from /usr/local/bin/pod:23:in `<main>'
	19: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'ffi' (>= 1.3.0) among 79 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/rajohns/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
```

**Comment by rajohns08** [comment]
Updating Xcode didn't work. I think I'm on an outdated version of CocoaPods. Updating that now.

**Comment by pratikbaid3** [comment]
Hi @rajohns08 .The suggested version of cocoapods that the project has been tested on is '1.9'. Could you alternatively try the "For iOS" steps mentioned in the readme.

**Comment by rajohns08** [comment]
Right - that's what i'm doing. I got past the above error by updating cocoapods to version 1.10.1. Now when I run the pod install step in the "For iOS" section, I see:

```
% pod install
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.framework: No such file or directory
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.podspec: No such file or directory
Analyzing dependencies
[!] No podspec found for `Flutter` in `Flutter`
```

**Comment by pratikbaid3** [comment]
Please run ```flutter pub get```
before running ```pod install```. This issue is related to the packages not being installed

**Comment by rajohns08** [comment]
Resluts below:

```
% flutter pub get
Changing current working directory to: /Users/rajohns/Developer/rutorrent-flutter
Running "flutter pub get" in rutorrent-flutter...                   0.4s

% pod install
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.framework: No such file or directory
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.podspec: No such file or directory
Analyzing dependencies
[!] No podspec found for `Flutter` in `Flutter`
```

**Comment by pratikbaid3** [comment]
@rajohns08 After running ```flutter pub get``` run ```cd ios``` from the root of the project and then run ```pod install --verbose```

**Comment by pratikbaid3** [comment]
You are running ```pod install``` from outside the ios directory.

**Comment by pratikbaid3** [comment]
@rajohns08 are you running ```pod install``` after going into the ios directory. The pod install wouldn't work without ```cd ios```

**Comment by rajohns08** [comment]
I'm running `pod install` inside `ios`. Here is the full console:

```
rajohns@Adams-MBP ios % flutter pub get
Changing current working directory to: /Users/rajohns/Developer/rutorrent-flutter
Running "flutter pub get" in rutorrent-flutter...                   0.4s

rajohns@Adams-MBP ios % pod install
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.framework: No such file or directory
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.podspec: No such file or directory
Analyzing dependencies
[!] No podspec found for `Flutter` in `Flutter`
```

**Comment by pratikbaid3** [comment]
Please try these steps:
1- Delete Podfile and Podfile.lock from ios folder

2- Flutter clean either from terminal or from Android studio -> Tools -> Flutter -> Flutter Clean

3- Pod install

4- Run the app

**Comment by rajohns08** [comment]
Results after first deleting Podfiles:

```
rajohns@Adams-MBP ios % flutter clean
Changing current working directory to: /Users/rajohns/Developer/rutorrent-flutter
Cleaning Xcode workspace...                                         2.5s
Deleting build...                                                    1ms
Deleting .dart_tool...                                               0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms

rajohns@Adams-MBP ios % pod install
[!] No `Podfile' found in the project directory.
```

**Comment by pratikbaid3** [comment]
Please run ```flutter pub get``` before running ```pod install```

**Comment by rajohns08** [comment]
Results below:

```
rajohns@Adams-MBP ios % flutter clean
Changing current working directory to: /Users/rajohns/Developer/rutorrent-flutter
Cleaning Xcode workspace...                                         1.9s
Deleting build...                                                    1ms
Deleting .dart_tool...                                               0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms

rajohns@Adams-MBP ios % flutter pub get
Changing current working directory to: /Users/rajohns/Developer/rutorrent-flutter
Running "flutter pub get" in rutorrent-flutter...                   0.4s

rajohns@Adams-MBP ios % pod install
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.framework: No such file or directory
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.podspec: No such file or directory
Analyzing dependencies
[!] No podspec found for `Flutter` in `Flutter`
```

**Comment by rajohns08** [comment]
```
rajohns@Adams-MBP ios % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2020.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
```

**Comment by pratikbaid3** [comment]
Please make sure you are following these steps in the correct order:

1. Delete ios folder from the root directory ```/ios```
2. From the root directory ```flutter create -i swift --project-name rutorrent .```
3. Run ```flutter pub get```
3. Uncomment ```platform :ios, '9.0'``` from ios/Podfile
4. Cd into the new ios directory```cd ios```
5. From the ios directory ```pod install --verbose```

**Comment by rajohns08** [comment]
Results:

1. First deleted `/ios`
2. Then below (I made sure to uncomment the line you said in step 4)
```
rajohns@Adams-MBP rutorrent-flutter % flutter create -i swift --project-name rutorrent .
Recreating project ....
  ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  ios/Runner/Info.plist (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  ios/Runner/Base.lproj/Main.storyboard (created)
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  ios/Flutter/Debug.xcconfig (created)
  ios/Flutter/Release.xcconfig (created)
  ios/Flutter/AppFrameworkInfo.plist (created)
  ios/.gitignore (created)
  ios/Runner/Runner-Bridging-Header.h (created)
  ios/Runner/AppDelegate.swift (created)
  ios/Runner.xcodeproj/project.pbxproj (created)
Running "flutter pub get" in rutorrent-flutter...                   0.5s
Wrote 41 files.

All done!
[✓] Flutter: is fully installed. (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 12.4)
[!] Android Studio: is partially installed; more components are available. (version 4.1)
[!] IntelliJ IDEA Community Edition: is partially installed; more components are available. (version 2020.1.3)
[✓] Connected device: is fully installed. (1 available)

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.

rajohns@Adams-MBP rutorrent-flutter % flutter pub get
Running "flutter pub get" in rutorrent-flutter...                   0.4s
rajohns@Adams-MBP rutorrent-flutter % cd ios 

rajohns@Adams-MBP ios % pod install --verbose
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.framework: No such file or directory
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.podspec: No such file or directory
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

Fetching external sources
-> Fetching podspec for `Flutter` from `Flutter`
[!] No podspec found for `Flutter` in `Flutter`

/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:989:in `fetch_external_source'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:968:in `block (2 levels) in fetch_external_sources'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:967:in `each'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:967:in `block in fetch_external_sources'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:966:in `fetch_external_sources'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/bin/pod:23:in `load'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/bin/pod:23:in `<main>'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/bin/ruby_executable_hooks:22:in `eval'
/Users/rajohns/.rvm/rubies/ruby-2.6.6/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by pratikbaid3** [comment]
@rajohns08 is ```pod install --verbose``` working fine now?

**Comment by pratikbaid3** [comment]
@rajohns08 It seems that you have these files missing 
```
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.framework: No such file or directory
cp: /usr/local/bin/flutter/bin/cache/artifacts/engine/ios/Flutter.podspec: No such file or directory
```
  
You can refer to https://github.com/flutter/flutter/issues/55095#issuecomment-626315616

**Comment by rajohns08** [comment]
Yep, running `flutter precache` before `pod install` worked. I'll submit a documentation PR to close this out.

**Comment by harchani-ritik** [comment]
@rajohns08 Still working on this?

**Comment by rajohns08** [comment]
Sorry I got a little busy and haven’t had time.

**Comment by pratikbaid3** [comment]
Closing this since this issue is a code issue and not specific to this project.
