### ISSUE TITLE
shared_preferences: Failed to handle method call

### ISSUE THREAD

**Issue by rj-since-2000** [CCExtractor/rutorrent-flutter#89]
From the trace it looks like the new Threadpool implementation is the likely cause.

Steps to reproduce -
1. `Flutter run`
2. Enter url to login
3. In the main screen click on the switch mode button

Log
```
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): java.util.concurrent.RejectedExecutionException: Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@c5cdb16 rejected from java.util.concurrent.ThreadPoolExecutor@bf1c89f[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.commitAsync(MethodCallHandlerImpl.java:137)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:66)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/MethodChannel#plugins.flutter.io/shared_preferences(31423): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (31423): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@2ecc23e rejected from java.util.concurrent.ThreadPoolExecutor@bf1c89f[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1], null, java.util.concurrent.RejectedExecutionException: Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@2ecc23e rejected from java.util.concurrent.ThreadPoolExecutor@bf1c89f[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
E/flutter (31423): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/flutter (31423): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/flutter (31423): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/flutter (31423): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.commitAsync(MethodCallHandlerImpl.java:137)
E/flutter (31423): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:66)
E/flutter (31423): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (31423): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (31423): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (31423): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (31423): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (31423): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (31423): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/flutter (31423): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31423): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/flutter (31423): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (31423): )
E/flutter (31423): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:581
E/flutter (31423): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
E/flutter (31423): <asynchronous suspension>
E/flutter (31423): #2      MethodChannelSharedPreferencesStore.setValue
package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:30
E/flutter (31423): <asynchronous suspension>
```

**Comment by rj-since-2000** [comment]
I solved this issue by upgrading the shared_preferences plugin from `^2.0.3` to `^2.0.4`

@harchani-ritik I propose to apply this change.

**Comment by pranav1230** [comment]
I'm facing the same issue and using latest package :(

**Comment by pratikbaid3** [comment]
@pranav1230 could you elaborate and also send the error log

**Comment by pranav1230** [comment]
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: 'dart:async/future_impl.dart': Failed assertion: line 543 pos 12: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Future._completeError (dart:async/future_impl.dart:543:12)
#3      _completeOnAsyncError (dart:async-patch/async_patch.dart:264:13)
#4      MethodChannelSharedPreferencesStore.setValue (package:shared_preferences_platform_interface/method_channel_shared_preferences.dart)
<asynchronous suspension>

**Comment by pranav1230** [comment]
I'm trying to increment Quotation number(Using shared prefs to store the data.) after generating the Pdf on button click.

**Comment by pranav1230** [comment]
I'm using await and .then() together in _incrementCounter method.

**Comment by rj-since-2000** [comment]
> I'm facing the same issue and using latest package :(

This issue was resolved using `^2.0.4` version of the plugin.

**Comment by pratikbaid3** [comment]
@pranav1230 I am unable to recreate this issue in the current build. As suggested by @rj-since-2000, using the latest version of the shared preferences package resolved the issue

**Comment by pratikbaid3** [comment]
> I'm trying to increment Quotation number(Using shared prefs to store the data.) after generating the Pdf on button click.

Are you referring to functionality in this app. Because I don't think there is a "pdf generation" function in this app

**Comment by pratikbaid3** [comment]
@rj-since-2000 I am closing this issue since this already seems to be resolved.

**Comment by pratikbaid3** [comment]
@rj-since-2000 I am closing this issue since this already seems to be resolved.
